language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t ektadhakad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ektadhakad/docker-react npm run test
